x86/cpu/tdx: Fix link failure
When CONFIG_INTEL_TDX_HOST=y and CONFIG_CMA=n, the link of vmlinux fails as
follows.  Select CMA on INTEL_TDX_HOST to fix link failure.

> ld: mm/page_alloc.o: in function `alloc_contig_range':
> (.text+0x33bb): undefined reference to `start_isolate_page_range'
> ld: (.text+0x3500): undefined reference to `test_pages_isolated'
> ld: (.text+0x352a): undefined reference to `undo_isolate_page_range'
> make: *** [Makefile:1183: vmlinux] Error 1

Fixes: 492a45a1ca03 ("x86/cpu/tdx: Introduce config option for Intel TDX")
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>