KVM: TDX: undefined reference to 'cpus_booted_once_mask'
When !CONFIG_SMP, undefined reference to 'cpus_booted_once_mask' in
arch/x86/kvm/boot/seam/tdx.o as follows.
add #ifdef CONFIG_SMP to fix it.

     ld: arch/x86/kvm/boot/seam/tdx.o: in function `bitmap_equal':
  >> include/linux/bitmap.h:335: undefined reference to `cpus_booted_once_mask'
  >> ld: include/linux/bitmap.h:335: undefined reference to `cpus_booted_once_mask'
  >> ld: include/linux/bitmap.h:335: undefined reference to `cpus_booted_once_mask'

Reported-by: kernel test robot <lkp@intel.com>
Fixes: 5560e4911e50 ("KVM: TDX: Load and init TDX-SEAM module during boot")
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>