x86/paravirt: Explicitly include msr.h
native_write_msr() is defined in msr.h. Explicitly include avoid
dependency issues.

Without this fix some random configs trigger following compilation
issues.

x86/include/asm/paravirt.h:780:2:
error: implicit declaration of function ‘native_write_msr

Signed-off-by: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>