KVM: x86: Export kvm_hv_get_assist_page()
Because kvm_hv_verify_vp_assist() that svm/nested.c refers uses
kvm_hv_get_assist_page(), modpost fails as follows.  Export the symbol.

ERROR: modpost: "kvm_hv_assist_page_enabled" [arch/x86/kvm/kvm-amd.ko] undefined!

Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>