mm: fix link error of memfile_notifier
This patch fixes the following link error when CONFIG_MEMFILE_NOTIFIER=y.
memfile_notifier.c and mmu_notifier.c include the following line.
"DEFINE_STATIC_SRCU(srcu);"  Contrally to "STATIC", the macro is expanded
to line which generates non-static symbol of __pcpu_uniq_##name.
So memfile_notifier.o and mmu_notifier.o includes the same global symbol
of __pcpu_unique_srcu_srcu_data.

As quick fix, rename srcu in memfile_notifier to srcu_memfile.
The right fix is to fix DEFINE_STATIC_SRCU to not generate global symbol
somehow.

include/linux/srcutree.h defines DEFINE_STATIC_SRCU as follows.
        static DEFINE_PER_CPU(struct srcu_data, name##_srcu_data);      \
        is_static struct srcu_struct name =                             \
                __SRCU_STRUCT_INIT(name, name##_srcu_data)

include/linux/percpu-defs.h defines DEFINE_PER_CPU as follows.
        DEFINE_PER_CPU_SECTION(type, name, "")

        __PCPU_DUMMY_ATTRS char __pcpu_scope_##name;                    \
        extern __PCPU_DUMMY_ATTRS char __pcpu_unique_##name;            \
        __PCPU_DUMMY_ATTRS char __pcpu_unique_##name;                   \
        extern __PCPU_ATTRS(sec) __typeof__(type) name;                 \
        __PCPU_ATTRS(sec) __weak __typeof__(type) name

symbols in memfile_notifier.o and mmu_notifier.o
  memfile_notifier.o:0000000000000000 D __pcpu_unique_srcu_srcu_data
  mmu_notifier.o:0000000000000000 D __pcpu_unique_srcu_srcu_data

Error:
    LD      vmlinux.o
  ld: mm/memfile_notifier.o:(.discard+0x0): multiple definition of `__pcpu_unique_srcu_srcu_data'; mm/mmu_notifier.o:(.discard+0x0): first defined here
  make: *** [/linux/Makefile:1158: vmlinux] Error 1

Fixes: 0a5ca94765e6 ("mm: Introduce memfile_notifier")
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>